"""create tickets table

Revision ID: e07f08d4399d
Revises:
Create Date: 2026-08-26 21:53:14.416630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e07f08d4399d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column(
            "ticket_id", sa.BigInteger(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'open'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')",
            name="tickets_priority_allowed",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'resolved', 'closed')",
            name="tickets_status_allowed",
        ),
        sa.CheckConstraint(
            "title = btrim(title) AND char_length(title) BETWEEN 3 AND 100",
            name="tickets_title_format",
        ),
        sa.CheckConstraint("updated_at >= created_at", name="tickets_timestamp_order"),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(
        "tickets_status_ticket_id_idx", "tickets", ["status", "ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("tickets_status_ticket_id_idx", table_name="tickets")
    op.drop_table("tickets")
    # ### end Alembic commands ###
