"""add users and ticket ownership

Revision ID: e98825c4d6b6
Revises: e07f08d4399d
Create Date: 2026-09-02 20:27:17.558020

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e98825c4d6b6"
down_revision: Union[str, Sequence[str], None] = "e07f08d4399d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role", sa.Text(), server_default=sa.text("'member'"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('member', 'admin')", name="users_role_allowed"),
        sa.CheckConstraint(
            "email = btrim(email) AND email = lower(email) AND char_length(email) BETWEEN 3 AND 254",
            name="users_email_format",
        ),
        sa.CheckConstraint("updated_at >= created_at", name="users_timestamp_order"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email", name="users_email_key"),
    )
    op.add_column("tickets", sa.Column("owner_id", sa.BigInteger(), nullable=True))
    op.create_index(
        "tickets_owner_id_status_ticket_id_idx",
        "tickets",
        ["owner_id", "status", "ticket_id"],
        unique=False,
    )
    op.create_foreign_key(
        "tickets_owner_id_fkey",
        "tickets",
        "users",
        ["owner_id"],
        ["user_id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tickets_owner_id_fkey", "tickets", type_="foreignkey")
    op.drop_index("tickets_owner_id_status_ticket_id_idx", table_name="tickets")
    op.drop_column("tickets", "owner_id")
    op.drop_table("users")
    # ### end Alembic commands ###
